parameters:
    chat_table: '%core.table_prefix%ajax_chat'
    chat_session_table: '%core.table_prefix%ajax_chat_sessions'
    
services:
    spaceace.ajaxchat.listener:
        class: spaceace\ajaxchat\event\listener
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@auth'
            - '@request'
            - '@controller.helper'
            - '@config'
            - '@config_text'
            - '@ext.manager'
            - '@path_helper'
            - '@service_container'
            - '%chat_table%'
            - '%chat_session_table%'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@spaceace.ajaxchat.chat.controller'
        tags:
            - { name: event.listener }
    spaceace.ajaxchat.chat.controller:
        class: spaceace\ajaxchat\controller\chat
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@auth'
            - '@request'
            - '@controller.helper'
            - '@config'
            - '@ext.manager'
            - '@path_helper'
            - '@service_container'
            - '%chat_table%'
            - '%chat_session_table%'
            - '%core.root_path%'
            - '%core.php_ext%'
    spaceace.ajaxchat.cron.task.prune_ajaxchat:
        class: spaceace\ajaxchat\cron\task\prune_ajaxchat
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@log'
            - '%core.table_prefix%'
        calls:
            - [set_name, [cron.task.prune_ajaxchat]]
        tags:
            - { name: cron.task }
